version: "3.8"
services:
  frontend:
    build:
      context: ../thesis-frontend
      dockerfile: Dockerfile
    container_name: thesis_frontend
    ports:
      - 3001:3000
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thesis_backend
    env_file:
      - .env.container
    depends_on:
      - mysql
    ports:
      - 8001:8000
    networks:
      - db-network
  mysql:
    image: mysql:latest
    container_name: thesis_mysql
    env_file:
      - .env.database
    ports:
      - 3307:3306
    networks:
      - db-network
    volumes:
      - thesis_mysql:/var/lib/mysql

  
networks:
  db-network:
volumes:
  thesis_mysql:
