version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thesis_backend
    env_file:
      - .env.container
    depends_on:
      - mysql
    ports:
      - 8001:8000
    networks:
      - thesis-network
  mysql:
    image: mysql:latest
    container_name: thesis_mysql
    env_file:
      - .env.database
    ports:
      - 3307:3306
    networks:
      - thesis-network
    volumes:
      - thesis_mysql:/var/lib/mysql

  
networks:
  thesis-network:
volumes:
  thesis_mysql:
